name: Gilded Rose Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./js-jest
        run: npm install
        
      - name: Run Tests
        working-directory: ./js-jest
        run: npm test
      
      - name: Jest Coverage Commenter + edit
        uses: k-chunghwan/jest-coverage-action@v1.1.2_rc
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          test_command: "npm run test:coverage"

